### ISSUE TITLE
Enhance python script interface to read multiple input data types.

### ISSUE THREAD

**Issue by davidfillmore** [NCAR/MET#1056]
As of met-8.0, the MET tools are able to call python scripts to read a gridded data file, load it into a NumPy array, define metadata, and pass it back to MET through memory.
<br/>

<br/>
However, this logic only works when Python stores that data as double-precision floating point values (i.e. "float64" in Python).  Passing integers or single-precision floats (i.e. "float32" in Python) results in either a segfault or unexpected behavior in MET.
<br/>

<br/>
This task is to update the logic in MET to figure out the Python data type that was used and interpret the data values correctly when loading them into a DataPlane object.
<i>[MET-1056] created by johnhg</i>

**Comment by rgbullock** [comment]
There is a member function "const char * Python3_Numpy::dtype() const" in the Python3_Numpy class that returns a string specifying the numeric data type specified in the numpy array.  The code can essentially switch on this as shown in the attached table.

[numpy_types.pdf](https://github.com/NCAR/MET/files/3870939/numpy_types.pdf)

**Comment by rgbullock** [comment]
Ok, the python numpy code now supports numpy arrays of integer type size 1, 2,4 or 8 bytes, signed or unsigned, and single or double precision floating-point types.  The data can be either little endian or big endian.


[load_numpy.pdf](https://github.com/NCAR/MET/files/3923985/load_numpy.pdf)

[ifelse.pdf](https://github.com/NCAR/MET/files/3923987/ifelse.pdf)
