### ISSUE TITLE
Reimplement DIA-Post for HRD as a new MET-TC tool named tc-rmw.

### ISSUE THREAD

**Issue by davidfillmore** [NCAR/MET#1085]
Reimplement DIA-Post tool from HRD to convert model output to storm-relative coordinates.
<br/>
  - This would be a new tool in MET, perhaps named "tc-rmw".
<br/>
  - Create a new tool in MET to read a model output file, define a point of interest, and convert the user-configurable field in RMW space (optionally, could get location info from ATCF).
<br/>
  - That&#39;s centered on the lat/lon of interest and do an azimuthal average over multiple heights and radii.
<br/>
  - Optionally, normalize by the radius of maximum winds.
<br/>
  - Optionally, potentially normalize the y-axis as well.  This is NOT typically done, but theoretically you could normalize by max inflow level (from Evan K).
<br/>
  - Tangential wind and radial wind would need to be derived.
<br/>
  - Write the output to a NetCDF file.
<br/>
  - This tool should process multiple output times in a single run... up to the the number of output times contained in the track.
<i>[MET-1085] created by johnhg</i>

**Comment by TaraJensen** [comment]
Charge 277046

**Comment by lisagoodrich** [comment]
Original JIRA attachment location:
https://sdg.rap.ucar.edu/jira/browse/MET-1085?filter=12903

[HWRF_PBL_scheme_Review20190126.pdf](https://github.com/NCAR/MET/files/3292241/HWRF_PBL_scheme_Review20190126.pdf)

**Comment by dwfncar** [comment]
Initial beta version ready for validation.
Remaining tc_rmw tasks have been added in issues 1172, 1173, 1174, 1175.
