### ISSUE TITLE
Support verification of hurricanes by normailzing data based on storm size.

### ISSUE THREAD

**Issue by davidfillmore** [NCAR/MET#1087]
- When comparing model output to either a gridded analysis or point observations, Evan would like to normailze by the storm size.  He&#39;d like to convert both the forecast and observation data into RMW space, using the ATCF A-Deck and B-Deck storm locations and sizes to do so.
<br/>
   - One option would be to enhance support for defining TILES of data.  The idea is to extract a tile of data centered on some location, i.e. hurricane center lat/lon.  In the METplus storm relative use case, we hard code the tile size as 30 degrees X 30 degrees.  The change would be letting the user pick the tile dimensions (i.e. 30x30) but pick the actual location of those points based on the size of the storm.  We could read the output of TC-Pairs to get the paired fcst/obs track information.
<br/>
   - Additionally, it would be convenient to define masking regions for this data relative to the storm size.  So you could easily define a donut of normalized points around the eyewall.
<br/>
   - This seems pretty well-defined for grid-to-grid comparisons, but perhaps a little less so for point observations.  You&#39;d normalize the gridded forecast data, but then have to maps the point obs lat/lon to a normalized forecast storm location.
<i>[MET-1087] created by johnhg</i>

**Comment by TaraJensen** [comment]
Charge 277046

**Comment by dwfncar** [comment]
Overlap with issue 1085.  TC_RMW tool done except for further testing and documentation.
