### ISSUE TITLE
Write a new tool in MET to aggregate the output of tc-rmw across multiple cases, rmw-analysis.

### ISSUE THREAD

**Issue by davidfillmore** [NCAR/MET#1092]
The new tc-rmw is described in <a href="https://sdg.rap.ucar.edu/jira/browse/MET-1085" title="Reimplement DIA-Post for HRD as a new MET-TC tool named tc-rmw." class="issue-link" data-issue-key="MET-1085">MET-1085</a>.
<br/>

<br/>
We need a new tool read the output of tc-rmw and average results across multiple cases.  Consider also including the standard deviation or variance.  Could also consider min/max and percentiles.
<br/>

<br/>
Not sure if a new tool is actually needed... or whether we can enhance the other MET tools to read this output... and then enhance those to compute means and other summary stats.
<br/>

<br/>

<br/>

<i>[MET-1092] created by johnhg</i>

**Comment by TaraJensen** [comment]
charge 277046

**Comment by dwfncar** [comment]
This issue is a duplicate of 1178.
