### ISSUE TITLE
Grid-Diag: Write a new tool to inventory data across multiple input gridded data sets and create a PDF and percentiles.

### ISSUE THREAD

**Issue by davidfillmore** [NCAR/MET#1106]
This is work for the S2S project and also supports percentile thresholding.
<br/>

<br/>
Write a new tool inv_data_plane (or perhaps grid_diag) to read multiple input gridded data files, extract one or more fields of data from each, including multiple vertical levels, subset into one or more masking subdomains, and report the PDF for each.
<br/>

<br/>
What should this tool be named?  It computes the relationship between two fields of data.  Perhaps "inventory_data_plane" or "diag_data_plane"?
<br/>

<br/>
Add a config file to store the options for this.
<br/>

<br/>
Bin the data into a user-configurable size for each field.
<br/>

<br/>
Let the user select the percentile bin width and the PDF bin width.  Require that the PDF bin width is an even multiple of percentile bin width so that we only need to keep track of the percentile bin counts.
<br/>

<br/>
Should we report the results in ASCII or NetCDF?
<br/>

<br/>
For each field, keep track of the counts in each bin.  Report the counts and/or normalized data for each bin.
<br/>

<br/>
We also need to compute PW vs Total Precip.  For each grid point, read the PW and Total Precip values.  They may or not be from the same input data file.  For obs, get precip from CMORPH and PW from SSMIS.  
<br/>

<br/>
Would be nice to be able to regrid the data as well.
<br/>

<br/>
Sample config file:
<br/>

<br/>
field = [
<br/>
   { name = "APCP"; level = "A06"; },
<br/>
   { name = "PW"; level = "L0"; },
<br/>
   { name = "RH"; level = [ "P1000", "P800", "P500", "P200" ]; }
<br/>
];
<br/>
perc_bin_size = 1.0;
<br/>

<br/>
Would produce 6 PDF&#39;s of the data on the output.
<br/>

<br/>
But you can also define an independent variable field...
<br/>
indy_field = { name = "PW"; level = "L0"; };
<br/>

<br/>
And that will produce 6 additional outputs.  For each of the 6 "dependent" fields above, keep track of the paired (indy_field value, dep_field value).  Bin this data by the indy field value and keep track of the mean of the dep_field values for each bin.
<br/>

<br/>
For each indy_field bin, report the mean of the dependent field values within that bin.
<br/>

<br/>
Weiwei confirms that we only need to support 0 or 1 independent fields at a time.
<i>[MET-1106] created by johnhg</i>

**Comment by TaraJensen** [comment]
Tara's visual brain dump of the tool - this may change
![image](https://user-images.githubusercontent.com/23195803/59942862-0a0c0380-941e-11e9-9d8c-ea0cb252cdff.png)

**Comment by TaraJensen** [comment]
From Pat Skinner - NSSL - 6/21/19

a description of how I could see using it is below: 

The first example I thought of was for creating UH climatologies for different CLUE members (or any CAMs with different configurations).  Ideally, we'd be able to point to a directory of grib or netcdf files, provide a field to aggregate, number of bins/range of values, and have bin counts/PDF/CDF info returned as either a separate file or stored in memory (which I think you had outlined on the slide).  This would be enormously useful for identifying thresholds for fields like UH or simulated reflectivity that can have dramatically different climatologies for different model configurations as well as identifying coverage/intensity biases in these quantities.

**Comment by TaraJensen** [comment]
Sitting in a meeting with NRL S2S and ESPC folks and just wanted to point out that the data_inventory should be able to be computed over multiple masking regions as well as specifying the time series either through the list of files or a METplus use-case.

**Comment by JohnHalleyGotway** [comment]
We should discuss this more.  Is there a need for users to define a climatology of their datasets, by computing the mean/stdev and perhaps percentiles at each individual grid point.  Does that functionality belong in this tool or elsewhere?  We'd want the climo info for each variable, level, and time of day.

**Comment by dwfncar** [comment]
In MET9_beta3.
