### ISSUE TITLE
Interpolating AOD at 550nm wavelength from 440 and 675 using logarithmic interpolation

### ISSUE THREAD

**Issue by hsoh-u** [NCAR/MET#1121]
From Partha:
Majority of the stations report at 440nm, 500 nm or at 675nm. Standard procedure to get 550nm from 440 and 675 is to use logarithmic interpolation.

Following method is known as angstrom power law and it assumes we have both 440 and 675 AOD's available :

     a_675_440  = -log(aerdata(i)%aot_675nm/                 & aerdata(i)%aot_440nm)/log(675./440.)
     aerdata(i)%aot_550nm  = aerdata(i)%aot_440nm*           & ((550./440.)**(-a_675_440))

So it calculates angstrom exponent at 675-440 first and then use that to calculate AOD at 550nm. AERONET does provide angstrom values at 440-675, but we are not using them (which is in separate file) but calculating them as an intermediate step. 

However, one can use a simplified log scale interpolation to calculate AOD at 550nm (which is a 1 liner). Based on equation 5 of this pdf : https://www.cmu.edu/biolphys/deserno/pdf/log_interpol.pdf
550aod = AODat870 ^f * AODat440^ 1-f
where f = a/a+b, and in this case a=550-440 = 110 and b = 675-550=125, a+b=235

One more thing, we need to make sure valid data available for both 675 and 440 at that location. Sometimes, "-999" is present in the data fields and we need to make sure to reject those before calculating AOD 550nm.

**Comment by TaraJensen** [comment]
Charge 2780541

**Comment by hsoh-u** [comment]
Created feature_1121_aod_interpolation branch and checked in

**Comment by hsoh-u** [comment]
feature_1121_aod_interpolation branch is merged to develop and master_v8.1 branches.

**Comment by malfailakawi2** [comment]
Hello,

I just wanted to make sure here when you wrote this:
550aod = AODat870 ^f * AODat440^ 1-f

Did you mean (AODat675) instead of (AODat870)?

I was confused because all the calculations were made using AODat675 and AOD440 except for that..

Can you please confirm

Thanks a lot in advance.

**Comment by bikegeek** [comment]
Hello,
I don't understand your question and need some clarification.  Is this
question in reference to something in the MET User's Guide, a config file
for a MET tool, or something else?

Regards,
Minna
---------------
Minna Win
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------
Pronouns: she/her

**Comment by malfailakawi2** [comment]
Hi,

Yeah I am sorry about that, I am enquiring about the logarithmic interpolation of the aerosol optical depth (AOD) at 550 nm.

If you can see this page:
https://github.com/dtcenter/MET/issues/1121

You will see that a way was proposed:
 (550aod = AODat870 ^f * AODat440^ 1-f) where f = a/a+b, and in this case a=550-440 = 110 and b = 675-550=125, a+b=235

I was wondering if AODat870 is indeed right because all other calculations (of a and b) are using AODat440 and AODat675 to find AODat550.

Thanks a lot.
Regrads

**Comment by bikegeek** [comment]
Thank you very much for the clarification. I'm assigning this to Howard
Soh, who created that comment in the Github Issue.

Regards,
Minna
---------------
Minna Win
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------
Pronouns: she/her

**Comment by malfailakawi2** [comment]
Thank you very much

I really appreciate it

**Comment by hsoh-u** [comment]
MET interpolates 550nm AOD from 440nm and 675nm AOD values. Please let us know if 870nm AOD is mentioned to interpolate 550nm AOD at the user guide or any other MET documents.

The description was just a copy of the original e-mail request from Partha Bhattacharjee. AODat870 will be a typo by the  requester.

**Comment by malfailakawi2** [comment]
Yeah I thought so.

Thanks a lot for the modification and clarification!

Regards,
Mohammed

**Comment by faisalalnasser13** [comment]
Hello, the library looks great, do you have any intentions of developing a python one? Also, I'm interested in applying the 440 675 interpolation, could you guide me to a paper or a document that specifies how is it calculated.

Thanks
