### ISSUE TITLE
Enhance ascii2nc to read points observation via Python embedding.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/MET#1122]
This is one of the ways we need to enhance MET's python embedding, enabling us to read point observations through python.  This was recently requested by NRL via met-help and needs to be included in met-9.0:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=89970

**Comment by JohnHalleyGotway** [comment]
On 6/10/2019, we had a telecon to discuss space weather work.
They would like to utilize Python embedding of point observations in Point-Stat.
Their models write output in a variety of binary data formats, but they run IDL to dump their gridded data out into ascii.  So they need a Python script to read these ascii files and pass them to MET via memory.
The point observations are in ascii as well.  And this is the data that we'd read into Point-Stat via python.

**Comment by TaraJensen** [comment]
Charge 2700001
