### ISSUE TITLE
Enhance PREPBUFR to derive additional observation quantities

### ISSUE THREAD

**Issue by davidfillmore** [NCAR/MET#608]
Originally reported in <a href="https://sdg.rap.ucar.edu/jira/browse/MET-428" title="Enhance MET tools for use at NCEP" class="issue-link" data-issue-key="MET-428"><strike>MET-428</strike></a>
<br/>

<br/>
Enhance PREPBUFR to derive additional observation quantities such as cloud base height (needs further definition of fields to be derived - look at notes from meetings with Perry)
<br/>

<br/>
This is still required by NCEP/MMB but we may need to call their module PREPFITS to do this or else there will be significant recoding involved I think*
<i>[MET-608] created by jensen</i>

**Comment by hsoh-u** [comment]
Created pb2nc_derived branch.
- Added two files: calcape.f & calpbl.f.
- Modified two files: Makefile.am& pb2nc.cc

**Comment by hsoh-u** [comment]
pb2nc_derived branch was merged to develop and master_v8.1 branches.
