### ISSUE TITLE
Enhance pcp_combine to compute the min, max, mean, or percentiles of many fields.

### ISSUE THREAD

**Issue by davidfillmore** [NCAR/MET#692]
The pcp_combine tool can be used to...
<br/>
(1) subtract two fields
<br/>
(2) add an arbitrary number of fields together
<br/>
(3) or sum up the same field across multiple files
<br/>

<br/>
This task is to enhance pcp_combine to perform additional operations on multiple fields.  In addition to "add", support min, max, mean, and any specified percentile.
<br/>

<br/>
This came up via a met-help ticket:
<br/>
   <a href="https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=78559">https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=78559</a>
<br/>

<br/>
One question is whether or not we should allow multiple operations in the same run.  For example...
<br/>
   -min -max -mean -add file1 field1 file2 field2 filen fieldn
<br/>

<br/>
And then write out all of those outputs into the same output file.
<br/>

<i>[MET-692] created by johnhg</i>

**Comment by JohnHalleyGotway** [comment]
This functionality was added in the met-8.1 release using the pcp_combine -derive command line option.
