### ISSUE TITLE
Add back in support for compiling MET on an IBM using xlf/xlC

### ISSUE THREAD

**Issue by davidfillmore** [NCAR/MET#742]
John recently gained access to an IBM machine at the Rhenish Institute for Environmental Research in Cologne, Germany.  Use this access to test MET there.
<br/>

<br/>
Ensure that 6.0 compiles on it and, if possible, post patches for version 5.2.
<br/>

<br/>
Also update the 6.0 online tutorial with IBM info.
<br/>

<i>[MET-742] created by johnhg</i>

**Comment by lisagoodrich** [comment]
Original attachment area in JIRA
https://sdg.rap.ucar.edu/jira/browse/MET-742?filter=12903

![TMP_Z2](https://user-images.githubusercontent.com/33230218/59537908-463ae380-8eb5-11e9-9ddf-7cbc82640b10.png)

**Comment by JohnHalleyGotway** [comment]
Closed but will not fix.
