### ISSUE TITLE
Consider enhancing STAT-Analysis to read (some) VSDB data files.

### ISSUE THREAD

**Issue by davidfillmore** [NCAR/MET#755]
For met-6.0, we&#39;ve enhanced STAT-Analysis to read output from multiple versions of MET.  The header columns for each version are read from a static data file, such as met_header_columns_V6.0.txt.
<br/>

<br/>
We could add entries for old line types - namely the format of the SL1L2, VL1L2, and FHO VSDB lines produced by NCEP.  That would enable STAT-Analysis to read/process VSDB data.
<br/>

<br/>
I tried it out this morning, and after adding one minor error check in parsing time strings, it actually worked.
<br/>

<br/>
Some issues are... 
<br/>
(1) For TSOILT and WSOILT variables, the level column is empty in the VSDB data and that throws off the parsing logic.  But for all the other variables (whose column values are filled in correctly), STAT-Analysis is able to parse SL1L2 lines and aggregate them.
<br/>

<br/>
(2) The LINE_TYPE column for FHO in VSDB files is stored as "FHO>0.1.  STAT-Analysis would need to parse those as separate columns.
<br/>

<br/>
Adding "full" support for reading VSDB data would require
<br/>
(1) Add a new table file which defines the VSDB header columns
<br/>
(2) Add logic to STAT-Analysis to distinguish between .stat (or .txt) and .vsdb suffixes.  If vsdb, handle parsing of FHO>0.1".
<br/>

<br/>
Is this something worth doing?  Since EMC is spinning up on METViewer, which already does this aggregation, perhaps they&#39;d never actually use STAT-Analysis anyway.
<br/>

<br/>
The other big issue would be line types that MET doesn&#39;t currently have.  Reading SL1L2, SAL1L2, VL1L2, VAL1L2, and FHO would be very well-defined and straight-forward.  But reading other line types and knowing how to process their values would not.  That could lead to a lot of work that we don&#39;t really want to do.
<br/>

<br/>
So is it worth doing the easy part of it... or not worth doing since it may lead to requests for things we don&#39;t want to do?  And we want them to switch over to using MET anyway.
<i>[MET-755] created by johnhg</i>

**Comment by lisagoodrich** [comment]
Original JIRA attachment area:
https://sdg.rap.ucar.edu/jira/browse/MET-755?filter=12903

[met_header_columns_V01.txt](https://github.com/NCAR/MET/files/3292108/met_header_columns_V01.txt)

**Comment by JohnHalleyGotway** [comment]
This issue was closed because we decided NOT to do this work or consider it for the future.
