### ISSUE TITLE
Use valgrind to search for memory issues in MET.

### ISSUE THREAD

**Issue by davidfillmore** [NCAR/MET#816]
A recent met_help question (<a href="https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=80492">https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=80492</a>) prompted us to run valgrind to debug a memory issue.  
<br/>

<br/>
Here&#39;s the valgrind command for mode and I&#39;ve attached the valgrind output:
<br/>

<br/>
valgrind --leak-check=full --show-leak-kinds=all --error-limit=no met-6.0_bugfix/bin/mode ${TEST_OUT_DIR}/pcp_combine/sample_fcst_12L_2005080712V_12A.nc ${TEST_OUT_DIR}/pcp_combine/sample_obs_2005080712V_12A.nc config/MODEConfig_APCP_12 -outdir ${TEST_OUT_DIR}/mode -v 2 > & mode_bugfix.log 
<br/>

<br/>
There are *many* issues that could be addressed in this output.  This task is assigned to both met-6.1 and met-6.0_bugfix.  If we find/fix critical issues, they could be distributed as a bugfix.
<br/>

<br/>
Suggest enhancing the nightly build to include the option of running the MET tools through valgrind to check them all for memory problems.
<i>[MET-816] created by johnhg</i>

**Comment by lisagoodrich** [comment]
Original JIRA attachment location:
https://sdg.rap.ucar.edu/jira/browse/MET-816?filter=12903

[mode_bugfix.log](https://github.com/NCAR/MET/files/3292335/mode_bugfix.log)

**Comment by hsoh-u** [comment]
I wonder if we handle the case  n_values is zero at get_percentiles() (src/libcode/vx_shapedata/interest.cc.

From John HG:
Practically speaking, n_values can never be zero in this context.  We call get_percentiles() to compute the percentile of raw data values inside a MODE object.  MODE objects, by definition, must have area >= 1, meaning that n_values would also be >= 1.  That being said, weird things can happen.  Checking for the degenerate case at line 617 would be a fine addition:
```
       if(n_values == 0) {
          mlog << Error << "\nget_percentiles() -> "
               << "the object is empty\n\n";
          exit(1);
       }
617 
618    //
619    // Allocate memory
620    //
621    v = new double [n_values];
```

**Comment by hsoh-u** [comment]
The source code were updated with #1385, #1358, and #1357.
No source code change on this issue.
